version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/kpt
      - rubygems:/kpt/vendor/bundle
      - npm_packages:/kpt/node_modules
    command: ['bundle', 'exec', 'rails', 's', '-b', '0.0.0.0']
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:10.4
    expose:
      - '5432'
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  rubygems:
  npm_packages:
  db_volume:
