version: '3'

services:
  rails:
    build: .
    command: bin/rails s
    depends_on:
      - db
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - rubygems:/usr/src/app/vendor/bundle

  frontend:
    build: .
    command: yarn run watch
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  db:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  rubygems:
  node_modules:
  postgresql:
